#!/bin/sh
set -e

# generate correct pid file, for versions where was non or incorrect
if [ "$1" = "upgrade" ] && [ "$2" ] && dpkg --compare-versions "$2" <= "1.12-1"; then
	pidof dns-flood-detector > /var/run/dns-flood-detector.pid
fi
#DEBHELPER#
